name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - wandb=0.16.5
  - mlflow=2.11.3
  - hydra-core=1.3.2
  - pip=24.0
  - pip:
      - hydra-joblib-launcher==1.2.0
